<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="caster_wheel_radius" value="${wheel_radius / 2.0}" />

    <link name="base_link" />

    <link name="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    
    <link name="chassis">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    

    <link name="laser_base_link">
        <visual>
            
            <geometry>
                <cylinder radius="0.05" length="0.05" />
            </geometry>
            <origin xyz="0 0 0.025" rpy="0 0 0" />
            <material name="blue" />
            
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.05" />
            </geometry>
            <origin xyz="0 0 0.025" rpy="0 0 0" />
            <xacro:cylinder_inertia m="0.1" r="0.05" l="0.1" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" l="${2*wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    
    <xacro:wheel_link prefix="left" />

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="0.5" r="${2*caster_wheel_radius}" 
                              xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_footprint_base_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <joint name="laser_base_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_base_link"/>
        <origin xyz=" 0 0 0.2" rpy="0 0 0"/>
    </joint>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="chassis" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(-base_width / 2.0) - (wheel_length / 2.0) } 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="chassis" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width / 2.0) + (wheel_length / 2.0) } 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="chassis" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 ${-caster_wheel_radius}" rpy="0 0 0" />
    </joint>

</robot>