<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.5" />
    <xacro:property name="base_width" value="1.0" />
    <xacro:property name="base_height" value="1.5" />
    

  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <material name="green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>

  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>


  <xacro:macro name="box_inertia" params="m l w h xyz rpy">
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}" />
            <mass value="${m}" />
            <inertia ixx="${(m/12)*(h*h + l*l)}" ixy="0" ixz="0"
                     iyy="${(m/12)*(w*w + l*l)}" iyz="0" 
                     izz="${(m/12)*(h*h + w*w)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r l xyz rpy">
      <inertial>
          <origin xyz="${xyz}" rpy="${rpy}" />
          <mass value="${m}" />
          <inertia ixx="${(m/12)*(3*r*r + l*l)}" ixy="0" ixz="0"
                   iyy="${(m/12)*(3*r*r + l*l)}" iyz="0" 
                   izz="${(m/2)*(r*r)}" />
      </inertial>
  </xacro:macro>

  <!-- Link 1 -->
  <link name="link1">
    <visual>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}" />
        </geometry>
        <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        <material name="blue" />
    </visual>
    <collision>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}" />
        </geometry>
        <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </collision>
    <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                       xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
</link>

<link name="link2">
  <visual>
      <geometry>
          <box size="0.5 0.25 0.25" />
      </geometry>
      <origin xyz="0 0 0.125" rpy="0 0 0" />
      <material name="blue" />
  </visual>
  <collision>
      <geometry>
          <box size="0.5 0.25 0.25" />
      </geometry>
      <origin xyz="0 0 0.125" rpy="0 0 0" />
  </collision>
  <xacro:box_inertia m="5.0" l="1.0" w="0.5" h="0.5"
                     xyz="0 0 0.125" rpy="0 0 0" />
</link>

<link name="pendullum">
  <visual>
      
    <geometry>
        <cylinder radius="0.05" length="1.0" />
    </geometry>
      <origin xyz="0 0 -0.5" rpy="0 0 0" />
      <material name="red" />
  </visual>
  <collision>
    <geometry>
      <cylinder radius="0.05" length="1.0" />
    </geometry>
      <origin xyz="0 0 -0.5" rpy="0 0 0" />
  </collision>
  <xacro:cylinder_inertia m="1.0" r="0.05" l="1.0" 
                                    xyz="0 0 -0.5" rpy="0 0 0" />
</link>

 
  <!-- World -->
  <link name="world"/>

  <!-- World fixed joint-->
  <joint name="world_fixed" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="world"/>
    <child link="link1"/>
    <dynamics friction = "0.01" damping="0.01"/>
  </joint>

  
  <joint name="link1_2_fixed" type="fixed">
    <origin xyz="0.125 0 1.5" rpy="0 0 0"/>
    <parent link="link1"/>
    <child link="link2"/>
    
  </joint>

  <joint name="link2_pendullum_joint" type="revolute">
    <origin xyz="0.3 0 0.125" rpy="0 0 0"/>
    <parent link="link2"/>
    <child link="pendullum"/>
    <axis xyz="1 0 0"/>
    <dynamics friction = "0.05" damping="0.05"/>
    <limit velocity="4.8" effort="2.4" lower="${-pi*0.8}" upper="${pi*0.8}" />
  </joint>


  

</robot>